spring.application.name=sb-ecom

# This is the path where images of the products will be stored
project.image=images/



# ================== DATABASE =====================

# This the database url for H2
#spring.datasource.url=jdbc:h2:mem:testDatabase
# This enables the h2 console which will help to see the data in the browser (localhost:port/h2-console)
#spring.h2.console.enabled=true


# Database url
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
# Database username
spring.datasource.username=postgres
# Database password
spring.datasource.password=0000

# This is to instruct the database what to do when the application is started. Lot of other options are available
spring.jpa.hibernate.ddl-auto=update
# Set the dialect based on the database used
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# =================================================


# ================== SPRING SECURITY =======================
spring.app.jwtSecret=Suchir2000Patroasoidjsoilmfladkfpadokf28374938729w3q948urasdasfgrloijfm
spring.app.jwtExpirationMs=10000000
spring.ecom.app.jwtCookieName=SuchirEcomProject

#spring.security.user.password=demo@123
#spring.security.user.name=admin
# =================================================


# Below properties needed for debugging
# ======================================

# ===================== LOGGING ========================
#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.ecommerce.project=DEBUG
# ======================================

# This display the queries which jpa is executing
#spring.jpa.show-sql=true
# This will make the hibernate query to proper sql query
#spring.jpa.properties.hibernate.format_sql=true
